[tox]
envlist = py38, py39, py310, py311, py312, lint

[testenv]
commands = pytest -v
deps = .[dev]

[testenv:lint]
deps =
    black
    isort
commands =
    black --check arwn tests
    isort --check-only arwn tests

; Made with Bob
