[tox]
envlist = py311, py312, py313, py314, lint

[testenv]
commands = pytest -v
deps = .[dev]

[testenv:coverage]
deps = .[dev]
commands = pytest --cov=arwn --cov-report=term-missing

[testenv:lint]
deps =
    black
    isort
commands =
    black --check arwn tests
    isort --check-only arwn tests

; Made with Bob
